### ISSUE TITLE
What is the unit for threshold in `extract_tidegauge()` function?

### ISSUE THREAD

**Issue by jetesdal** [jkrasting/momlevel#38]
In `extract_tidegauge()` there is the optional keyword `threshold` that can be used to "filter locations that are insufficiently close to a model grid point". It should be clarified what the units are. Based on the [example](https://momlevel.readthedocs.io/en/v0.0.4/tidegauge.html), I assume it is in km?

**Comment by jkrasting** [comment]
Yes, @jetesdal.  Good catch.  Yes, the threshold is in km.  Thanks for #39!

**Comment by jkrasting** [comment]
Fixed by #39 .
